### ISSUE TITLE
compatibility with k8s 1.20

### ISSUE THREAD

**Issue by iliaboti** [cernops/cvmfs-csi#38] opened 2022-07-01 08:09 UTC
I have been running cvmfs-sci successfully on 1.19. It does not run any more on 1.20 due to 

`unexpected error getting claim reference: selfLink was empty, can't make reference`

Looks like this is because of this:
https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/issues/25

Is anyone running CVMFS CSI on kubernetes 1.20+ and how ?

Thanks in advance,
Ioannis

**Comment by innovate-invent** [comment] 2022-08-26 02:40
I have been making an attempt at maintaining this driver: https://github.com/cernops/cvmfs-csi/pull/36

https://hub.docker.com/r/brinkmanlab/csi-cvmfsplugin/tags

**Comment by gman0** [comment] 2022-08-26 10:01
Hi @iliaboti, we are overhauling the driver in #39. The error is caused by an old version of Kubernetes client-go library used by some of the sidecars in the driver deployment that made some kube API calls. The new version of the driver has updated dependencies (and technically no longer does any API calls as these sidecars have been removed with the changes in driver design). Since the issue you're reporting won't be relevant anymore, I'm closing it. Please feel free to reopen, or open another one if you have comments or questions.

**Closed by gman0** 2022-08-26 10:01 UTC
